version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: db_alquileres_paysandu
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alquileres_paysandu
    ports:
      - "5432:5432"
    volumes:
      - pgdata_alquileres:/var/lib/postgresql/data

volumes:
  pgdata_alquileres: